# This is used in case of ansible and helm.
# using {{}} for place holders.
apiVersion: v1
kind: Service
metadata: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.service.app }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}